import os
import json
import requests
from flask import Flask, render_template, request, jsonify, Response, stream_with_context
from werkzeug.utils import secure_filename
import PyPDF2
import docx
import io

app = Flask(__name__)
app.config['MAX_CONTENT_LENGTH'] = 32 * 1024 * 1024  # 32MB max upload
app.config['SECRET_KEY'] = 'docmind-secret-key'

OLLAMA_BASE_URL = os.environ.get('OLLAMA_URL', 'http://localhost:11434')

ALLOWED_EXTENSIONS = {'txt', 'pdf', 'doc', 'docx', 'md', 'html', 'csv', 'json'}

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def extract_text_from_file(file, filename):
    ext = filename.rsplit('.', 1)[1].lower()
    
    if ext == 'pdf':
        reader = PyPDF2.PdfReader(io.BytesIO(file.read()))
        text = ''
        for page in reader.pages:
            text += page.extract_text() + '\n\n'
        return text.strip() or '[No extractable text found in PDF]'
    
    elif ext == 'docx':
        doc = docx.Document(io.BytesIO(file.read()))
        return '\n\n'.join([para.text for para in doc.paragraphs if para.text.strip()])
    
    elif ext in ('txt', 'md', 'html', 'csv', 'json'):
        return file.read().decode('utf-8', errors='ignore')
    
    return file.read().decode('utf-8', errors='ignore')


def build_prompt(content, style):
    styles = {
        'explainer': 'Create a clear, engaging HTML page that explains the content step by step with headings, key concepts highlighted, callout boxes, and helpful examples.',
        'summary':   'Create a concise HTML summary with an executive overview, bullet-point key takeaways, important statistics, and a quick-reference section.',
        'study':     'Create a study guide HTML with sections for key concepts, definitions, important facts, review questions, and a memory-aid summary.',
        'presentation': 'Create a visually structured HTML that reads like slides — each main point as a distinct full-width card with large headings and concise content.',
        'technical': 'Create technical documentation HTML with overview, detailed sections, code blocks where relevant, parameters/options tables, and a reference index.',
    }
    instruction = styles.get(style, styles['explainer'])

    return f"""You are an expert at converting raw content into beautiful, well-structured, standalone HTML pages.

TASK: Convert the content below into a complete, self-contained HTML file.
STYLE: {instruction}

STRICT REQUIREMENTS:
- Output ONLY valid HTML — no markdown fences, no explanation, no preamble
- Start with <!DOCTYPE html> and end with </html>
- Include ALL CSS inside a <style> tag in the <head>
- Use Google Fonts (import via @import in CSS)
- Beautiful modern design: clean typography, good spacing, subtle colors
- Use semantic HTML: header, main, section, article, footer
- Highlight key terms with <mark> or styled <span>
- Include a page header with title and a footer with "Generated by DocMind"
- Make it responsive (mobile-friendly)
- NO external JS dependencies — pure HTML+CSS only in output
- Use tasteful accent colors, cards, and visual hierarchy

CONTENT TO CONVERT:
---
{content[:8000]}
---

OUTPUT (complete HTML file only):"""


# ─── Routes ──────────────────────────────────────────────

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/generate')
def generate_page():
    return render_template('generate.html')

@app.route('/history')
def history_page():
    return render_template('history.html')

@app.route('/settings')
def settings_page():
    return render_template('settings.html')


# ─── API ─────────────────────────────────────────────────

@app.route('/api/models')
def get_models():
    try:
        r = requests.get(f'{OLLAMA_BASE_URL}/api/tags', timeout=5)
        r.raise_for_status()
        data = r.json()
        models = [m['name'] for m in data.get('models', [])]
        return jsonify({'ok': True, 'models': models})
    except requests.exceptions.ConnectionError:
        return jsonify({'ok': False, 'error': 'Cannot connect to Ollama. Make sure it is running.'}), 503
    except Exception as e:
        return jsonify({'ok': False, 'error': str(e)}), 500


@app.route('/api/extract', methods=['POST'])
def extract_text():
    if 'file' not in request.files:
        return jsonify({'ok': False, 'error': 'No file uploaded'}), 400
    file = request.files['file']
    if file.filename == '':
        return jsonify({'ok': False, 'error': 'No file selected'}), 400
    if not allowed_file(file.filename):
        return jsonify({'ok': False, 'error': 'File type not supported'}), 400
    try:
        filename = secure_filename(file.filename)
        text = extract_text_from_file(file, filename)
        return jsonify({'ok': True, 'text': text, 'filename': filename})
    except Exception as e:
        return jsonify({'ok': False, 'error': f'Failed to extract text: {str(e)}'}), 500


@app.route('/api/generate', methods=['POST'])
def generate():
    data = request.get_json()
    content = data.get('content', '').strip()
    model   = data.get('model', '')
    style   = data.get('style', 'explainer')

    if not content:
        return jsonify({'ok': False, 'error': 'No content provided'}), 400
    if not model:
        return jsonify({'ok': False, 'error': 'No model selected'}), 400

    prompt = build_prompt(content, style)

    def stream():
        try:
            resp = requests.post(
                f'{OLLAMA_BASE_URL}/api/generate',
                json={'model': model, 'prompt': prompt, 'stream': True},
                stream=True,
                timeout=120
            )
            resp.raise_for_status()
            for line in resp.iter_lines():
                if line:
                    try:
                        obj = json.loads(line.decode('utf-8'))
                        token = obj.get('response', '')
                        if token:
                            yield f"data: {json.dumps({'token': token})}\n\n"
                        if obj.get('done'):
                            yield f"data: {json.dumps({'done': True})}\n\n"
                    except json.JSONDecodeError:
                        continue
        except requests.exceptions.ConnectionError:
            yield f"data: {json.dumps({'error': 'Lost connection to Ollama'})}\n\n"
        except Exception as e:
            yield f"data: {json.dumps({'error': str(e)})}\n\n"

    return Response(stream_with_context(stream()), mimetype='text/event-stream',
                    headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'})


if __name__ == '__main__':
    app.run(debug=True, port=5000, threaded=True)
